name: CI
on:
  push:
    branches:
      - main
      - spike/*
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
